### ISSUE TITLE
Command line argument with ArgParse

### ISSUE THREAD

**Issue by neizod** [neizod/duppub#4]
Right now the script can be invoke with only one argument, the CSV file.

It'd be nice if we can invoke it and supply more arguments to tune the performance, such as

- Threshold (default: 80%) -- report similarity only above this threshold.
- Limit Characters (default: 100 chars) -- right now the algorithm run so slow we need to chop string to compare down, we should be able to tune this parameter.
- Algorithm (default: `levenshtein`) -- other slower algorithm available is `edit_distant`.

Technical info: now the `main` function doing the hard code parsing argument with `sys.argv`, I think Python `ArgParse` can do this job better & cleaner.

**Comment by Alex-CodeLab** [comment]
Considered using `docopt` ?

**Comment by bmsauer** [comment]
I've submitted a pull request for this.  I left the part about actually using the variables out; I just stored them in a local 'config' var for now.  The script works as it did before the pr.  

https://github.com/neizod/duppub/pull/5

**Comment by neizod** [comment]
@Alex-CodeLab is it better than standard module?

**Comment by Alex-CodeLab** [comment]
@neizod It both works. but docopt is easier to use; just define the options in a docstring and you're done. 
see the video http://docopt.org/

**Comment by neizod** [comment]
@Alex-CodeLab looks promising! are you interest in submitting a PR?
